name: pipeline
on:
    push:
        branches:
            - master
jobs:
    test-php7:
        name: Run tests on PHP 7.0.33
        runs-on: ubuntu-20.04
        container: antriver/php:7.0.33
        steps:
            -   name: Composer install
                run: composer install
            -   name: Run tests
                run: composer test
    test-php8:
        name: Run tests on PHP 8.0.12
        runs-on: ubuntu-20.04
        container: antriver/php:8.0.12
        steps:
            -   name: Composer install
                run: composer install
            -   name: Run tests
                run: composer test
